/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
//#include "stm32f401xe.h"

#define PERIPH_BASE       0x40000000UL
#define AHB1PERIPH_BASE   (PERIPH_BASE + 0x00020000UL)
#define GPIOA_BASE        (AHB1PERIPH_BASE + 0x0000UL)
#define RCC_BASE          (AHB1PERIPH_BASE + 0x3800UL)

// Registres GPIO (entré/sortie)
#define GPIOA_MODER       *((volatile uint32_t*)(GPIOA_BASE + 0x00))	// mode : input/output
#define GPIOA_ODR         *((volatile uint32_t*)(GPIOA_BASE + 0x14))	// output data

// Registres RCC (entrées/sorties)
#define RCC_AHB1ENR       *((volatile uint32_t*)(RCC_BASE + 0x30))
#define RCC_AHB1ENR_GPIOAEN (1 << 0)  // Bit pour activer GPIOC



#define DELAY_COUNT 500000

int main(void)
{
    // 1. Activer horloge GPIOA
    RCC_AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    // 2. Configurer PA5 en sortie
    GPIOA_MODER &= ~(0x3 << (5 * 2)); 	// clear mode
    GPIOA_MODER |=  (0x1 << (5 * 2)); 	// output mode

    /* Loop forever */
    while(1)
    {
    	// Allume LED (PC13 = 0 sur Nucleo)
    	GPIOA_ODR &= ~(1 << 5);
        for (volatile int i = 0; i < DELAY_COUNT; i++); // simple delay

        // Éteint LED
        GPIOA_ODR |= (1 << 5);
        for (volatile int i = 0; i < DELAY_COUNT; i++);
    }
}
